### ISSUE TITLE
关于光源投影矩阵的计算

### ISSUE THREAD

**Issue by lwj-cg** [AirGuanZ/GAMES202#1]
你好，请问一下光源投影矩阵的计算是让它正好包裹住模型的AABB包围盒吗？

**Comment by AirGuanZ** [comment]
原则上，在不引起artifact的条件下，包裹的范围越小，效果越好。理想情况下应该恰好包住“可见的场景在光源视角下的投影体”与“光源本身照明范围”的交集。我这里用的是一个小范围的聚光灯，就直接让它包住了光源范围，算是偷了个懒。

**Comment by lwj-cg** [comment]
谢谢大佬的回复，考虑方向光的话，如果只是让光源fit to scene的话还有一个问题，就是近处的人物在shadow map中只占很小的范围，导致人物阴影出现严重的锯齿。我听说过级联阴影贴图之类的解决方案，但是不确定它在渲染人物阴影时精度是否够用。想请教一下渲染高精度的人物阴影时一般是怎么做的，有没有什么可以参考的资料。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Z ***@***.***&gt;; 
发送时间: 2021年4月24日(星期六) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AirGuanZ/GAMES202] 关于光源投影矩阵的计算 (#1)





 
原则上，在不引起artifact的条件下，包裹的范围越小，效果越好。理想情况下应该恰好包住“可见的场景在光源视角下的投影体”与“光源本身照明范围”的交集。我这里用的是一个小范围的聚光灯，就直接让它包住了光源范围，算是偷了个懒。

**Comment by AirGuanZ** [comment]
如果用了级联仍然觉得人物阴影精度不够，那这应该是凑在摄像机面前的人物，可以考虑单独给ta开一张shadowmap。我在这方面的实践也很有限，就不乱推荐资料了。
