### ISSUE TITLE
cmake 不成功

### ISSUE THREAD

**Issue by weiyu666** [AirGuanZ/GAMES202#2]
不好用环境配置需要什么吗？已经是按照readmd上面的做了
![image](https://user-images.githubusercontent.com/22174508/126034342-b94e4b3a-5f21-42ae-a7ed-55b59a477125.png)

**Comment by AirGuanZ** [comment]
git clone的时候是否忘记添加`--recursive`选项了？这会导致子模块缺失。

**Comment by weiyu666** [comment]
现在是可以啦之前我记得是加过--recursive选项了的，后来删掉原来的从新clone 按照你wiki的步骤命令行下执行就可以啦!
![image](https://user-images.githubusercontent.com/22174508/126689334-0256edf4-011f-4e17-ab64-be940d6bc4b0.png)
问题二：
![image](https://user-images.githubusercontent.com/22174508/126690025-7dfbd562-7150-4c58-a6e8-e95fd71046de.png)
VS2019会默认使用HLSL编译器对其进行编译，而.fx文件中并未定义main函数，所以会导致编译出错怎么办？

**Comment by AirGuanZ** [comment]
噢，我用了一个cmake 3.18才引入的功能`VS_SETTINGS`，用它来避免hlsl文件被编译。不过我cmake文件里的版本号标低了，抱歉，已修正这个问题，你更新cmake到新版本应该就可以了。

**Comment by weiyu666** [comment]
我的cmake还必须3.18 以上才可以是吗？
![image](https://user-images.githubusercontent.com/22174508/128639782-c3b7b861-95b4-4298-ae10-e33f185c6d5a.png)

**Comment by weiyu666** [comment]
用3.20版本已经可以啦没事啦~ 提一个题外话：“能不能更详细说一下你做的这个？文档写多一下 没用过dx”

**Comment by AirGuanZ** [comment]
如果有闲心我可能会写相关的文章，最近忙于毕业。不过这些代码也就看个原理，要真讲太细了可能202助教要来查水表😂

**Comment by weiyu666** [comment]
大佬有没有作业写一个分析的博客比较什么的？share一下呀？毕业？本科吗可以加个好友私下探讨一下吗？
